{
 "title": "Speedtest results",
 "description": "Display speedtest.net results (ping, upload and download speed)",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Average download speed / week",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "download_mbs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "Average upload speed / week",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "upload_mbs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "Last Locations (Distance)",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "limit": "3",
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       { "params": [ "Location" ], "type": "alias" }
      ],
      [
       { "params": [ "distance" ], "type": "field" },
       { "params": [ "Distance" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "Average ping latency / week",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "query": "SELECT mean(\"value\") FROM \"download\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "Upload / Download",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download_mbs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_mbs" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "Ping",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Ping",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  },
  {
   "title": "All Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "query": "SELECT last(\"serverid\") AS \"Server ID\", last(\"location\") AS \"Location\", last(\"distance\") AS \"Distance\",last(\"ping\") AS \"Ping\", last(\"download_mbs\") AS \"Download\", last(\"upload_mbs\") AS \"Upload\" FROM \"speedtest\" WHERE (\"host\" = 'local') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "location" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Location" ], "type": "alias" }
      ],
      [
       { "params": [ "distance" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Distance" ], "type": "alias" }
      ],
      [
       { "params": [ "serverid" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Server ID" ], "type": "alias" }
      ],
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Ping" ], "type": "alias" }
      ],
      [
       { "params": [ "download_mbs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Download" ], "type": "alias" }
      ],
      [
       { "params": [ "upload_mbs" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "local" }
     ]
    }
   ]
  }
 ]
}